version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules # Exclusion de node_modules
    environment:
      - NODE_ENV=development
      - MONGODB_URI= mongodb+srv://ramihsasna34:sIkqeCP9EoVq6o4u@ecommercedb.amgbv.mongodb.net/?retryWrites=true&w=majority&appName=ecommerceDB
    depends_on:
      - mongo
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules # Exclusion de node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
